apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: machineconfigpools.machineconfiguration.openshift.io
spec:
  conversion:
    strategy: None
  group: machineconfiguration.openshift.io
  names:
    kind: MachineConfigPool
    listKind: MachineConfigPoolList
    plural: machineconfigpools
    shortNames:
    - mcp
    singular: machineconfigpool
  scope: Cluster
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: MachineConfigPool describes a pool of MachineConfigs.
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: MachineConfigPoolSpec is the spec for MachineConfigPool resource.
            properties:
              configuration:
                description: configuration is the current configuration of machines
                  in the pool
                properties:
                  name:
                    description: name is the name of the rendered MachineConfig object
                      for the pool
                    type: string
                  source:
                    description: source is the list of MachineConfig objects that
                      were used to generate the rendered config
                    items:
                      properties:
                        apiVersion:
                          type: string
                        kind:
                          type: string
                        name:
                          type: string
                        namespace:
                          type: string
                        resourceVersion:
                          type: string
                        uid:
                          type: string
                      type: object
                    type: array
                type: object
              machineConfigSelector:
                description: machineConfigSelector is a label selector to filter MachineConfig
                  objects
                type: object
                x-kubernetes-preserve-unknown-fields: true
              nodeSelector:
                description: nodeSelector is a label selector to filter nodes
                type: object
                x-kubernetes-preserve-unknown-fields: true
              paused:
                description: paused specifies whether or not changes to this machine
                  config pool should be stopped
                type: boolean
            type: object
          status:
            description: MachineConfigPoolStatus is the status for MachineConfigPool
              resource.
            properties:
              conditions:
                description: conditions represents the latest available observations
                  of current state
                items:
                  properties:
                    lastTransitionTime:
                      format: date-time
                      type: string
                    message:
                      type: string
                    reason:
                      type: string
                    status:
                      type: string
                    type:
                      type: string
                  type: object
                type: array
              configuration:
                description: configuration is the current configuration of machines
                  in the pool
                properties:
                  name:
                    description: name is the name of the rendered MachineConfig object
                      for the pool
                    type: string
                  source:
                    description: source is the list of MachineConfig objects that
                      were used to generate the rendered config
                    items:
                      properties:
                        apiVersion:
                          type: string
                        kind:
                          type: string
                        name:
                          type: string
                        namespace:
                          type: string
                        resourceVersion:
                          type: string
                        uid:
                          type: string
                      type: object
                    type: array
                type: object
              degradedMachineCount:
                format: int32
                type: integer
              machineCount:
                format: int32
                type: integer
              observedGeneration:
                format: int64
                type: integer
              readyMachineCount:
                format: int32
                type: integer
              unavailableMachineCount:
                format: int32
                type: integer
              updatedMachineCount:
                format: int32
                type: integer
            type: object
        type: object
    served: true
    storage: true
